server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";

        try_files $uri $uri/ =404;
    }
}